name: doharoots
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  animated_bottom_navigation_bar: 
  apple_sign_in: 
  badges: 
  cached_network_image: 
  cloud_firestore: 
  connectivity: 
  cupertino_icons: 
  dots_indicator:
  easy_localization: 
  firebase_auth: 
  firebase_core: 
  firebase_messaging: 
  firebase_storage: 
  flutter_custom_tabs: 
  flutter_facebook_login: 
  flutter_html: 
  flutter_icons: 
  flutter_widget_from_html: 
  google_fonts: 
  google_sign_in: 
  html: 
  html_unescape: 
  image_picker: 
  intl: 
  introduction_screen: 
  launch_review: 
  line_icons: 
  lottie: 
  md2_tab_indicator: 
  package_info: 
  path_provider: 
  provider: 
  share: 
  shared_preferences: 
  skeleton_text: 
  toast: 
  url_launcher: #^5.7.10
  youtube_player_flutter: 
  animated_progress_button: 
  rounded_loading_button: 
  firebase_analytics: 

  # firebase_admob: ^0.10.2
  # facebook_audience_network: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Doha Roots"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"




# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png
    - assets/news6.png
    - assets/news7.png
    - assets/logo.png
    - assets/done.json
    - assets/translations/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
